# Generated by Django 3.0.5 on 2020-05-02 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200502_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice',
            new_name='choice_name',
        ),
    ]
